version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto"
phases:
    install:
        commands:
            - yum install java-17-amazon-corretto-devel -y
            - update-alternatives --auto javac
            - update-alternatives --auto java
            - ls /usr/lib/jvm
    build:
        commands:
            - mvn test package
artifacts:
  files:
    - appspec.yml
    - scripts/*
    - target/chess-0.0.1-SNAPSHOT.jar
  discard-paths: yes
